version: '3'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: mysecretpassword
    ports:
      - 5050:80
  flask:
    build: ./flask
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: postgres://postgres:mysecretpassword@postgres/postgres
    ports:
      - 5000:5000
    depends_on:
      - postgres
volumes:
  postgres_data:
